config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'
  resources :flats do
    resources :bookings, only: [:new, :create]
    resources :reviews
  end

  # get 'flats', to: 'flats#index', as: :flats

  resources :bookings, only: [:index] do
    get "accept", to: "bookings#accept_booking"
    get "decline", to: "bookings#decline_booking"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user
  validates :start_date, :end_date, presence: true
  validates :number_of_guests, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
   return if end_date.blank? || start_date.blank?

   if end_date < start_date
     errors.add(:end_date, "must be after the start date")
   end
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user
  has_one_attached :photo
  monetize :price_in_cents, as: "price"
  validates :name, presence: true, uniqueness: { scope: :address }
  validates :city, presence: true
  validates :address, presence: true
  validates :price_in_cents, presence: true, numericality: { only_integer: true }
  validates :max_guests, presence: true
  geocoded_by :full_address
  after_validation :geocode, if: :will_save_change_to_address?

  def full_address
    "#{address}, #{city}"
  end

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [1, 2, 3, 4, 5]
  belongs_to :flat
  belongs_to :user
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: RATING }
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :flats
  has_many  :bookings
  has_many :reviews
  has_one_attached :photo
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user_bookings = policy_scope(Booking)
    if current_user.admin
      @user_flats = policy_scope(Flat)
    end
  end

  # def show
  # end

  def create
    @booking = Booking.new(booking_params)
    @flat = Flat.find(params[:flat_id])
    @booking.flat = @flat
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to flats_path
    else
      render "flats/show"
    end
  end

  # def edit
  # end

  # def update
  # end

  # def destroy
  # end

  def accept_booking
    @booking = Booking.find(params[:booking_id])
    @booking.status = true
    authorize @booking
    @booking.save
    redirect_to bookings_path
  end

  def decline_booking
    @booking = Booking.find(params[:booking_id])
    @booking.status = false
    authorize @booking
    @booking.save
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :number_of_guests)
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
   if params[:search].present?
      @flats = policy_scope(Flat).near(params[:search], 20)
    else
      @flats = policy_scope(Flat)
    end
    @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { flat: flat })
      }
    end
  end

  def show
    @booking = Booking.new
    @review = Review.new
    @reviews = Review.all
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    authorize @flat
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to root_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def flat_params
    params.require(:flat).permit(:name, :description, :city, :address, :price_in_cents, :max_guests, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @flats = Flat.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    @review = Review.new(review_params)
    @flat = Flat.find(params[:flat_id])
    authorize @review
    @review.user = current_user
    @review.flat = @flat
    if @review.save
      redirect_to flat_path(@flat)
    else
      render 'flats/show'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<div class="container">

  <div class="booking-section">
    <h1 class="page-title">My bookings</h1>
    <% @user_bookings.each do |booking| %>
      <div class="card-booking">
        <% if booking.flat.photo.blank? %>
          <div class="generic-flat">
          </div>
        <% else %>
          <%= cl_image_tag booking.flat.photo.key %>
        <% end %>

        <div class="card-booking-infos">
          <h2><%= booking.flat.name %></h2>
          <p>Check-in: <b><%= booking.start_date.strftime("%A %d %B %Y") %></b></p>
          <p>Check-out: Date: <b><%= booking.end_date.strftime("%A %d %B %Y") %></b></p>
        </div>

        <div class="card-booking-status">
          <% if booking.status == true %>
            <p>Booking status</p>
            <i class="far fa-check-circle"></i>
            <p id="status-confirmed">Confirmed</p>
          <% elsif booking.status == false %>
            <p>Booking status</p>
            <i class="far fa-times-circle"></i>
            <p id="status-declined">Declined</p>
          <% else %>
            <p>Booking status</p>
            <i class="far fa-clock"></i>
            <p id="status-pending">Pending</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Section host uniquement visible par l'admin -->

  <% if current_user.admin %>
    <div class="host-section">
      <h1 class="page-title">My guests</h1>
      <% @user_flats.each do |flat| %>
        <% flat.bookings.each do |booking| %>

          <div class="card-booking">
            <% if booking.flat.photo.blank? %>
              <div class="generic-flat">
              </div>
            <% else %>
              <%= cl_image_tag booking.flat.photo.key %>
            <% end %>

            <div class="card-booking-infos">
              <h2><%= booking.flat.name %></h2>
              <p>Your guest's name: <%= booking.user.first_name %></p>
              <p>Check-in: <b><%= booking.start_date.strftime("%A %d %B %Y") %></b></p>
              <p>Check-out: Date: <b><%= booking.end_date.strftime("%A %d %B %Y") %></b></p>
            </div>


            <% if booking.status == nil %>
              <div class="card-booking-status-guest">
                <p>Booking status</p>
                <div class="card-guest-status">
                  <%= link_to booking_accept_path(booking), class: 'no-deco', data: { confirm: "Are you sure you want to confirm this booking?" } do %>
                    <div class="status">
                      <i class="far fa-check-circle"></i>
                      <p id="status-confirmed">Confirm</p>
                    </div>
                  <% end %>
                  <%= link_to booking_decline_path(booking), class: 'no-deco', data: { confirm: "Are you sure you want to decline this booking?" } do %>
                    <div class="status">
                      <i class="far fa-times-circle"></i>
                      <p id="status-declined">Decline</p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% else %>
              <div class="card-booking-status">
                <% if booking.status == true %>
                  <div class="card-guest-status">
                    <div class="status-active">
                      <i class="far fa-check-circle"></i>
                      <p id="status-confirmed">Confirm</p>
                    </div>
                    <%= link_to booking_decline_path(booking), class: 'no-deco', data: { confirm: "Are you sure you want to change the booking status to 'Declined'?" } do %>
                      <div class="status">
                        <i class="far fa-times-circle"></i>
                        <p id="status-declined">Decline</p>
                      </div>
                    <% end %>
                  </div>
                <% else booking.status == false %>
                  <div class="card-guest-status">
                    <%= link_to booking_accept_path(booking), class: 'no-deco', data: { confirm: "Are you sure you want to change the booking status to 'Confirmed'?" } do %>
                      <div class="status">
                        <i class="far fa-check-circle"></i>
                        <p id="status-confirmed">Confirm</p>
                      </div>
                    <% end %>
                    <div class="status-active">
                      <i class="far fa-times-circle"></i>
                      <p id="status-declined">Decline</p>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>

          </div>

        <% end %>
      <% end %>
    </div>
  <% end %>

  <!-- fin de la section admin -->

</div>

app/views/flats/_info_window.html.erb
<% if flat.photo.present? %>
  <%= cl_image_tag flat.photo.key, class:'img-fluid' %>
<% end %>
<h5><%= flat.name %></h5>
<p><%= flat.address %></p>

app/views/flats/create.html.erb
<h1>Flats#create</h1>
<p>Find me in app/views/flats/create.html.erb</p>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-8 offset-sm-2">
      <h1 class="page-title">Edit your flat</h1>
      <%= simple_form_for @flat do |f| %>
        <%= f.input :name %>
        <%= f.input :description, as: :text %>
        <%= f.input :city %>
        <%= f.input :address %>
        <%= f.input :price_in_cents %>
        <%= f.input :max_guests %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'Publish', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container-fluid d-flex">
  <div class="cards">
    <h1 class="page-title">Check out all the available flats</h1>
    <div class="cards-query">
      <% @flats.each do |flat| %>
        <%= link_to flat_path(flat), class: 'card-decoration' do %>
          <% if flat.photo.blank? %>

            <div class="card-trip">
              <div class="card-category">
              </div>
              <div class="card-trip-infos">
                <div>
                  <h2><%= flat.name %></h2>
                  <p><%= flat.city %></p>
                </div>
                <h2 class="card-trip-pricing"><%= humanized_money flat.price %>€</h2>
                <% if flat.user.photo.blank? %>
                  <%= image_tag "user.png", class: 'card-trip-user avatar-bordered' %>
                <% else %>
                  <%= cl_image_tag flat.user.photo.key, class: 'card-trip-user avatar-bordered' %>
                <% end %>
              </div>
            </div>

          <% else %>

            <div class="card-trip">
              <%= cl_image_tag flat.photo.key %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= flat.name %></h2>
                  <p><%= flat.city %></p>
                </div>
                <h2 class="card-trip-pricing"><%= humanized_money flat.price %>€</h2>
                <% if flat.user.photo.blank? %>
                  <%= image_tag "user.png", class: 'card-trip-user avatar-bordered' %>
                <% else %>
                  <%= cl_image_tag flat.user.photo.key, class: 'card-trip-user avatar-bordered' %>
                <% end %>
              </div>
            </div>

          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <!-- map to be added here -->
  <div id="map" style="width: 40%" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-8 offset-sm-2">
      <h1 class="page-title">Publish a new flat</h1>
      <%= simple_form_for @flat do |f| %>
        <%= f.input :name %>
        <%= f.input :description, as: :text %>
        <%= f.input :city %>
        <%= f.input :address %>
        <%= f.input :price_in_cents %>
        <%= f.input :max_guests %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'Publish', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<% if policy(@flat).edit? %>
  <div class="container-fluid edit-bar">
    <!-- Bouton pour edit le flat -->
    <%= link_to edit_flat_path(@flat), class: 'edit-bar-button' do %>
      Edit your flat <i class="far fa-edit"></i>
    <% end %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <!-- Bouton declancheur de la modale -->
    <div class="edit-bar-button" data-toggle="modal" data-target="#exampleModal">
      Delete your flat <i class="far fa-trash-alt"></i>
    </div>
  </div>
<% end %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete confirmation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Deleting this flat will delete all current related bookings & reviews</p>
        <p>Are you sure you want to delete your flat:</p>
        <p><%= @flat.name %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= link_to flat_path(@flat), method: :delete do %>
          <button type="button" class="btn btn-primary">Delete my flat</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if @flat.photo.blank? %>
  <div class="flat-banner" style="background-color: #46cdcf">
  </div>
<% else %>
  <div class="flat-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @flat.photo.key %>');">
  </div>
<% end %>

<div class="container">
  <div class="flat">
    <div class="flat-info">
      <div class="flat-info-header">
        <div class="flat-info-header-title">
          <h2><%= @flat.name %></h2>
          <p class="city"><%= @flat.city %></p>
        </div>
        <div class="flat-info-header-avatar">
          <% if @flat.user.photo.blank? %>
            <%= image_tag "user.png", class: 'avatar' %>
          <% else %>
            <%= cl_image_tag @flat.user.photo.key, class: 'avatar' %>
          <% end %>
          <p class="owner"><%= @flat.user.first_name %></p>
        </div>
      </div>
      <p><i class="fas fa-user-friends"></i> <%= @flat.max_guests %> guests</p>
      <hr>
      <p><%= @flat.description %></p>

      <h2>Reviews</h2>
      <hr>
      <% if @flat.reviews.present? %>
        <div class="reviews">
          <% @flat.reviews.each do |review| %>
            <div class="review">
              <% if review.user.photo.present? %>
                <%= cl_image_tag review.user.photo.key, class: 'avatar' %>
              <% else %>
                <%= image_tag "user.png", class: 'avatar' %>
              <% end %>
              <p class="description"><%= review.content %></p>
              <p class="rating">
                <% review.rating.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
                <% (5 - review.rating).times do %>
                  <i class="far fa-star"></i>
                <% end %>
              </p>
            </div>
            <hr>
          <% end %>
        </div>
      <% else %>
      <i>There are no review for the moment</i>
      <% end %>
      <% if policy(Review).create? %>
        <hr>
        <div class="review-form">
          <%= simple_form_for [@flat, @review] do |f| %>
            <%= f.input :rating, collection: 1..5 %>
            <%= f.input :content, as: :text %>
            <%= f.submit 'Add review', class: 'btn btn-primary' %>
          <% end %>
        </div>
      <% end %>

    </div>
    <div class="flat-booking border bg-light rounded">
      <h3><%= humanized_money @flat.price %>€ <span style="font-size: 13px;">per night</span></h3>
      <hr>

      <!-- datepickr from online tuto -->
      <div id='flat-booking-dates' data-unavailable="<%= @flat.unavailable_dates.to_json %>">
        <%= simple_form_for([@flat, @booking]) do |f| %>
          <%= f.input :start_date, as: :string, type: :text, id: 'startDateInput' %>
          <%= f.input :end_date, as: :string, type: :text, id: 'endDateInput' %>
          <%= f.input :number_of_guests, collection: 1..@flat.max_guests, label: 'Number of guests' %>
          <%= f.submit 'Book now', class: 'btn btn-primary btn-lg btn-block' %>
        <% end %>
       </div>
      <!-- end of datepickr -->

      <%#= simple_form_for [@flat, @booking] do |f| %>
        <%#= f.input :start_date, as: :date, html5: true %>
        <%#= f.input :end_date,   as: :date, html5: true %>
        <%#= f.input :number_of_guests, collection: 1..@flat.max_guests, label: 'Number of guests' %>
        <%#= f.submit 'Book now', class: 'btn btn-primary btn-lg btn-block' %>
      <%# end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="banner">
    <div class="container">

      <div class="search-container">
        <%= simple_form_for :search, url: flats_path, method: :get do |f| %>
          <div class="search-form-control form-group">
            <input type="search" class="form-control string required" name="search" id="address-input" placeholder="Where are we going?" />
            <!--<input class="form-control string required" type="text" name="search" id="search_query" /> -->
            <button name="button" type="submit" class="btn btn-success">
            <i class="fas fa-search"></i> Search
            </button>
          </div>
        <% end %>
      </div>

    </div>
  </div>


<div class="container">
  <h1 class="page-title">Check out all the available flats</h1>

  <div class="cards-home">
    <% @flats.each do |flat| %>
      <%= link_to flat_path(flat), class: 'card-decoration' do %>
        <% if flat.photo.blank? %>

          <div class="card-trip">
            <div class="card-category">
            </div>
            <div class="card-trip-infos">
              <div>
                <h2><%= flat.name %></h2>
                <p><%= flat.city %></p>
              </div>
              <h2 class="card-trip-pricing"><%= humanized_money flat.price %>€</h2>
              <% if flat.user.photo.blank? %>
                <%= image_tag "user.png", class: 'card-trip-user avatar-bordered' %>
              <% else %>
                <%= cl_image_tag flat.user.photo.key, class: 'card-trip-user avatar-bordered' %>
              <% end %>
            </div>
          </div>

        <% else %>

          <div class="card-trip">
            <%= cl_image_tag flat.photo.key %>
            <div class="card-trip-infos">
              <div>
                <h2><%= flat.name %></h2>
                <p><%= flat.city %></p>
              </div>
              <h2 class="card-trip-pricing"><%= humanized_money flat.price %>€</h2>
              <% if flat.user.photo.blank? %>
                <%= image_tag "user.png", class: 'card-trip-user avatar-bordered' %>
              <% else %>
                <%= cl_image_tag flat.user.photo.key, class: 'card-trip-user avatar-bordered' %>
              <% end %>
            </div>
          </div>

        <% end %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="logo">
      <i class="fas fa-h-square"></i> MyBooKings
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>

        <li class="nav-item active">
          <%= link_to "Publish a flat", new_flat_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.blank? %>
            <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %>
    </ul>
  </div>
</div>